### PR TITLE
kawaii function

### PR DESCRIPTION
**Pull request by clownmoments**
has extra kawaii function, but I wanna make the user input optional, is that possible? also, does python have function overloading outside classes?

### CODE REVIEW

**Review by Lord-of-the-Galaxy — CHANGES_REQUESTED** [review]
Don't use `'lmao'` as the default value. The sensible thing to use is `None` or something else like that. _Not_ `'lmao'`. I'll merge after you make this change.
Also, I'll be merging into `dev` branch instead of `master`.

**Comment by clownmoments** [comment]
@Lord-of-the-Galaxy done

**Comment by clownmoments** [comment]
wait what happened

**Review by Lord-of-the-Galaxy — COMMENTED** [review]
Yeah, this works.

**Review by Lord-of-the-Galaxy — APPROVED** [review]
Accepted.

**Pull request merged**
